### ISSUE TITLE
id: users lawyer  -  on this and a couple other screens from stand-alone interviews, we say [user name] rather than "you" and it is awkward

### ISSUE THREAD

**Issue by VTskier** [LemmaLegalConsulting/docassemble-DivorceNoKids#137]
On this and the previous screen, we ask “does [**user name**] have a lawyer” instead of “do **you** have a lawyer.” This is because the question is pulled from a stand-alone interview that allows either the plaintiff or defendant to fill out the form.

How can I code it so that if the question shows up in our combined Divorce interview -- where the person is always the plaintiff -- it will ask “do you have a lawyer”?

**Comment by nonprofittechy** [comment]
Best / most flexible way is to add a custom version of the question to the `customized_screens.yml` file. This overrides all of the included interviews, just like you can override the ql_baseline.yml questions.

**Comment by nonprofittechy** [comment]
The "lowest" in the file takes priority.
