### ISSUE TITLE
Rearrange locations overflow info on addendum

### ISSUE THREAD

**Issue by VTskier** [LemmaLegalConsulting/docassemble-DivorceNoKids#181]
@nonprofittechy  Would you be able to help on this one?

For overflow items in locations, I need to arrange these fields from left to right to be:

- item.address.on_one_line()
- item.start_date
- item.end_date
- item.housemates

![image](https://github.com/LSVermont/docassemble-VTDivorce/assets/104463248/a3461e4d-6d3a-4b4a-ab26-38a27b774d5c)

**Comment by nonprofittechy** [comment]
Yes, I can take this one. I'll post a code example too
