### ISSUE TITLE
Interview gets stuck on 2nd screen on VTCourtForms.org

### ISSUE THREAD

**Issue by VTskier** [LemmaLegalConsulting/docassemble-DivorceNoKids#189]
@nonprofittechy I did some good updates and fixes related to VTDivorce and the interviews it depends on. It works from my Suffolk playground.

I updated the packages on VTCourtForms but the VTDivorce interview gets stuck on the 2nd screen. Can you see a reason why???

**Comment by nonprofittechy** [comment]
I'll take a look

**Comment by nonprofittechy** [comment]
I think this was fixed by upgrading to the most recent version of Docassemble. I could reproduce the problem you had on 1.4.103, but not on 1.4.102. And the latest that just came out this evening it works.
