### ISSUE TITLE
court address on complaint PDF -- add "Family Court" or similar in front of address

### ISSUE THREAD

**Issue by VTskier** [LemmaLegalConsulting/docassemble-DivorceNoKids#71]
Mia: I'm not sure what to do with this drop-down field in the Summons. Question number 6 on the form. We need to add the county name and Family Division before the address that we display. When you look at the PDF that is produced, the other options that the court had now get messed up. I'd like to keep those other options there for the user in case they need them, but maybe we can't. Maybe we have to make that a text field? The courts may not like that.

In this case, the words "Chittenden Family Division" should appear before the address. ALSO, if you download the final PDF and open it in Acrobat, that field is all messed up. Suggestions?
![image](https://github.com/LSVermont/docassemble-VTDivorce/assets/104463248/a045a9b1-790a-46fd-8790-add7825976c4)

**Comment by nonprofittechy** [comment]
@VTskier I'd recommend making this a text field. LMK if you want to check on this with the court first.
